// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneFoodBowl.web.Data;

namespace OneFoodBowl.web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200503023418_segunda")]
    partial class segunda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.CreatePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int?>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("CreatePlans");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int?>("GenderId");

                    b.Property<double>("Height")
                        .HasMaxLength(4);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<double>("Weight")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(9);

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int?>("RecipeTypeId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeTypeId");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.RecipeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int?>("RecipeTypeId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeTypeId");

                    b.ToTable("RecipeDetail");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.RecipeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("RecipeTypes");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Nutritionist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int?>("GenderId");

                    b.Property<DateTime>("HireDate");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Nutritionists");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.CreatePlan", b =>
                {
                    b.HasOne("OneFoodBowl.web.Data.Entities.Recipe", "Recipe")
                        .WithMany("CreatePlans")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.Customer", b =>
                {
                    b.HasOne("OneFoodBowl.web.Data.Entities.Gender", "Gender")
                        .WithMany("Customers")
                        .HasForeignKey("GenderId");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.Recipe", b =>
                {
                    b.HasOne("OneFoodBowl.web.Data.Entities.RecipeType", "RecipeType")
                        .WithMany()
                        .HasForeignKey("RecipeTypeId");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Entities.RecipeDetail", b =>
                {
                    b.HasOne("OneFoodBowl.web.Data.Entities.RecipeType", "RecipeType")
                        .WithMany("recipeDetails")
                        .HasForeignKey("RecipeTypeId");
                });

            modelBuilder.Entity("OneFoodBowl.web.Data.Nutritionist", b =>
                {
                    b.HasOne("OneFoodBowl.web.Data.Entities.Gender", "Gender")
                        .WithMany("Nutritionists")
                        .HasForeignKey("GenderId");
                });
#pragma warning restore 612, 618
        }
    }
}
